/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left thumb stick horizontal
      y: 0  # Left thumb stick vertical
    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0
    axis_angular:  
      yaw: 3  # Right thumb stick horizontal
    scale_angular:
      yaw: 0.4
    scale_angular_turbo:
      yaw: 1.0
    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
