/urg_node2:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    calibrate_time: false
    cluster: 1
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    error_reset_period: 5.0
    frame_id: laser
    publish_intensity: false
    publish_multiecho: false
    serial_baud: 115200
    serial_port: /dev/ttyACM0
    skip: 0
    synchronize_time: false
    time_offset: 0.0
    use_sim_time: false